# this is an example only, this must not be here
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  ORACLE_PASSWORD: cGFzc3dvcmRzbzE=
  APP_USER_PASSWORD: cGFzc3dvcmRhcHA=
