apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydatabase
spec:
  selector:
    matchLabels:
      app: mydatabase
  template:
    metadata:
      labels:
        app: mydatabase
    spec:
      volumes:
      - name: config-volume
        configMap:
          name: app-config
      containers:
      - name: mydatabase
        image: gvenzl/oracle-xe:21.3.0
        volumeMounts:
        - name: config-volume
          mountPath: /container-entrypoint-initdb.d
        env:
        - name: ORACLE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ORACLE_PASSWORD
        - name: APP_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_USER
        - name: APP_USER_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_USER_PASSWORD
        resources:
          limits:
            memory: "2Gi"
            cpu: "1"
        ports:
        - containerPort: 1521
---
apiVersion: v1
kind: Service
metadata:
  name: database-svc
spec:
  type: ClusterIP
  selector:
    app: mydatabase
  ports:
  - port: 1521
    targetPort: 1521